name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
              
      - name: Check docker-compose installation
        run: |
          ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} "if [ ! -f /usr/local/bin/docker-compose ]; then echo 'docker-compose not found. Please install it on the EC2 instance.'; exit 1; fi"

      - name: Deploy Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} 'cd ~/docker-compose-react-nodejs-mysql-master && sudo docker-compose up -d --build'
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
